graph RL;
    DeveloperMachine((Developer Machine))
    subgraph GitHub
        Repo[mitch-datasource Repository];
    end
    DeveloperMachine == Push Commits ==> Repo;
    Repo == Triggers Workflow ==> CICDService;
    subgraph Circle CI
        CICDService[CircleCI Service] ==> Build
        Build ==> Test
        Test ==> CommitAnalysis{Analyse Commits}
        CommitAnalysis ==>|Should Release| SemanticRelease[Semantic Release]
    end
    SemanticRelease -. Publishes To .-> npmpackage[mitch-datasource Package];
    SemanticRelease -. Tag Commit .-> Repo;
    SemanticRelease -. Create GitHub Release .-> Repo;
    subgraph NPM Registry
        npmpackage
    end