# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.13

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - restore_cache:
          keys:
            - v1-mitch-datasource-dependencies-{{ checksum "projects/mitch-datasource/package.json" }}
            - v1-mitch-datasource-dependencies-
      - restore_cache:
          keys:
            - v1-mitch-datasource-documentation-dependencies-{{ checksum "projects/mitch-datasource-documentation/package.json" }}
            - v1-mitch-datasource-documentation-dependencies-
      - restore_cache:
          keys:
            - v1-mitch-datasource-test-dependencies-{{ checksum "projects/mitch-datasource-test/package.json" }}
            - v1-mitch-datasource-test-dependencies-
      - restore_cache:
          keys:
            - v1-mitch-datasource-test-react-dependencies-{{ checksum "projects/mitch-datasource-test-react/package.json" }}
            - v1-mitch-datasource-test-react-dependencies-
      - restore_cache:
          keys:
            - v1-mitch-datasource-test-vue-dependencies-{{ checksum "projects/mitch-datasource-test-vue/package.json" }}
            - v1-mitch-datasource-test-vue-dependencies-
      - restore_cache:
          keys:
            - v1-mitch-datasource-test-utilities-dependencies-{{ checksum "projects/mitch-datasource-test-utilities/package.json" }}
            - v1-mitch-datasource-test-utilities-dependencies-

      - run: npm install
      - run: npm run install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - save_cache:
          paths:
            - projects/mitch-datasource/node_modules
          key: v1-mitch-datasource-dependencies-{{ checksum "projects/mitch-datasource/package.json" }}
      - save_cache:
          paths:
            - projects/mitch-datasource-documentation/node_modules
          key: v1-mitch-datasource-documentation-dependencies-{{ checksum "projects/mitch-datasource-documentation/package.json" }}
      - save_cache:
          paths:
            - projects/mitch-datasource-test/node_modules
          key: v1-mitch-datasource-test-dependencies-{{ checksum "projects/mitch-datasource-test/package.json" }}
      - save_cache:
          paths:
            - projects/mitch-datasource-test-react/node_modules
          key: v1-mitch-datasource-test-react-dependencies-{{ checksum "projects/mitch-datasource-test-react/package.json" }}
      - save_cache:
          paths:
            - projects/mitch-datasource-test-vue/node_modules
          key: v1-mitch-datasource-test-vue-dependencies-{{ checksum "projects/mitch-datasource-test-vue/package.json" }}
      - save_cache:
          paths:
            - projects/mitch-datasource-test-utilities/node_modules
          key: v1-mitch-datasource-test-utilities-dependencies-{{ checksum "projects/mitch-datasource-test-utilities/package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run Tests
          command: npm run test
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      # Releases the package. Note the change directory
      # is in the same command. If we put it as a separate
      # command, it won't actually change directory when releasing
      # due to the way CircleCI works.
      # For more information, see:
      #   https://discuss.circleci.com/t/unable-to-change-present-directory-or-cd-cmd-ignored/12537/4
      - run:
          name: Release package
          command: cd "./projects/mitch-datasource" && npx semantic-release -r 'https://github.com/deltoss/mitch-datasource.git'

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master