graph RL;
    mitch-datasource-documentation== Uses ==>mitch-datasource;
    mitch-datasource-test== Uses ==>mitch-datasource;
    mitch-datasource-test== Uses ==>mitch-datasource-test-utilities;
    mitch-datasource-test-react== Uses ==>mitch-datasource;
    mitch-datasource-test-react== Uses ==>mitch-datasource-test-utilities;
    mitch-datasource-test-vue== Uses ==>mitch-datasource;
    mitch-datasource-test-vue== Uses ==>mitch-datasource-test-utilities;