graph RL;
    DeveloperMachine((Developer Machine))
    subgraph GitHub
        Repo[mitch-datasource Repository];
    end
    DeveloperMachine == Push Commits ==> Repo;
    Repo == Triggers Workflow ==> CICDService;
    subgraph Circle CI
        CICDService[CircleCI Service] ==> Build
        Build ==> Test
        Test ==> NetlifyCli[Netlify CLI]
        Test ==> CommitAnalysis{Any Release Commits?}
        CommitAnalysis ==>|Yes| SemanticRelease[Semantic Release]
    end
    NetlifyCli == Deploys Docs ==> NetlifySite
    SemanticRelease -. Publishes To .-> npmpackage[mitch-datasource Package];
    SemanticRelease -. Tag Commit .-> Repo;
    SemanticRelease -. Create GitHub Release .-> Repo;
    subgraph Netlify
        NetlifySite[Netlify Site]
    end
    subgraph NPM Registry
        npmpackage
    end